/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 28 22:13:08 GMT 2018
 */

package dec2bin;

import org.junit.Test;
import static org.junit.Assert.*;
import dec2bin.Dec2Bin;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Dec2Bin_ESTest extends Dec2Bin_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[8];
      Dec2Bin.main(stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Dec2Bin dec2Bin0 = new Dec2Bin();
  }
}
